#!/bin/bash -eux

function setup_bosh_env_vars() {
  set +ux
  pushd bbl-state/"${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd
  set -ux
}

function close_bbl_ssh_connection() {
  # Kill all ssh connections on exit.
  # This is needed so that tasks using bbl print-env in a credhub environment
  # don't hang after the script is finished.
  pkill ssh || true
}

function update_runtime_config() {
  local vars
  vars=""
  for var in ${VARS}
  do
    vars="${vars} -v ${var}"
  done

  bosh \
    -n \
    update-runtime-config \
    ops-files/${RUNTIME_CONFIG} \
    ${vars}
  set -x
}

function main() {
  setup_bosh_env_vars
  update_runtime_config
}

trap close_bbl_ssh_connection EXIT

main ${PWD}

