#!/bin/bash -eux

function setup_bosh_env_vars() {
  set +ux
  pushd bbl-state/"${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd
  set -ux
}

function close_bbl_ssh_connection() {
  # Kill all ssh connections on exit.
  # This is needed so that tasks using bbl print-env in a credhub environment
  # don't hang after the script is finished.
  pkill ssh || true
}

function upload_release() {
  bosh \
    -n \
    upload-release \
    ${RELEASE}
  set -x
}

function main() {
  setup_bosh_env_vars
  upload_release
}

trap close_bbl_ssh_connection EXIT

main ${PWD}

