#!/bin/bash -exu

function check_input_params() {
  if [ -z "$BBL_STATE_DIR" ]; then
    echo "BBL_STATE_DIR has not been set"
    exit 1
  fi
}

function create_resources() {
  mkdir -p "env-repo/${BBL_STATE_DIR}"
  pushd "env-repo/${BBL_STATE_DIR}"

    # terraform
    mkdir -p terraform
    if [ -n "${TERRAFORM_CUSTOMISATIONS}" ]; then
      for CUSTOMISATION in ${TERRAFORM_CUSTOMISATIONS}; do
        cp ${root_dir}/bbl-customisations/${CUSTOMISATION} terraform/
      done
    fi 

    mkdir -p cloud-config
    if [ -n "${CLOUDCONFIG_CUSTOMISATIONS}" ]; then
      for CUSTOMISATION in ${CLOUDCONFIG_CUSTOMISATIONS}; do
        cp ${root_dir}/cloud-config-customisations/${CUSTOMISATION} cloud-config/
      done
    fi
    
  popd
}

function main() {
  local root_dir
  root_dir="${1}"
  check_input_params
  create_resources
}

main
