#!/bin/bash -exu

function check_input_params() {
  if [ -z "$BBL_STATE_DIR" ]; then
    echo "BBL_STATE_DIR has not been set"
    exit 1
  fi
}

function create_resources() {
  mkdir -p "env-repo/${BBL_STATE_DIR}"
  pushd "env-repo/${BBL_STATE_DIR}"

    # terraform
    mkdir -p terraform
    if [ -n "${TERRAFORM_CUSTOMISATIONS}" ]; then
      for CUSTOMISATION in ${TERRAFORM_CUSTOMISATIONS}; do
        cp ${root_dir}/terraform-customisations/${CUSTOMISATION} terraform/
      done
    fi 

    mkdir -p cloud-config
    if [ -n "${CLOUDCONFIG_CUSTOMISATIONS}" ]; then
      for CUSTOMISATION in ${CLOUDCONFIG_CUSTOMISATIONS}; do
        cp ${root_dir}/cloud-config-customisations/${CUSTOMISATION} cloud-config/
      done
    fi
    
  popd
}

function commit_bbl_state_dir {
  local root_dir
  root_dir="${1}"
  commit_message="${2}"

  pushd "${root_dir}/env-repo/${BBL_STATE_DIR}"
    if [[ -n $(git status --porcelain) ]]; then
      set_git_config
      git add --all .
      git commit -m "${commit_message}"
    fi
  popd

  pushd "${root_dir}"
    shopt -s dotglob
    cp -R env-repo/* updated-env-repo/
  popd
}

function set_git_config() {
  if [ -z "${GIT_COMMIT_USERNAME}" ]; then
    GIT_COMMIT_USERNAME="CI Bot"
  fi

  if [ -z "${GIT_COMMIT_EMAIL}" ]; then
    GIT_COMMIT_EMAIL="cf-release-integration@pivotal.io"
  fi

  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"
}

function main() {
  local root_dir
  root_dir="${1}"
  check_input_params
  create_resources
}

trap "commit_bbl_state_dir ${PWD} 'Update bbl state dir'" EXIT

main ${PWD}
