---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v4.12.0

inputs:
- name: metadata

outputs:
- name: email

run:
  path: concourse-tasks/tasks/create-status-email-bosy/task

params:
  STATUS: success
  EXTRA_CONTENT: 
  FILE: email.txt
