---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.0.0

inputs:
- name: concourse-tasks
- name: metadata
- name: start_time
- name: end_time
- name: cf-deployment
- name: cf-deployment-concourse-tasks

outputs:
- name: email

run:
  path: concourse-tasks/tasks/create-status-email-body/task

params:
  STATUS: success
  EXTRA_CONTENT: 
  FILE: email.txt
