---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.6.0

inputs:
- name: bbl-state
- name: concourse-tasks

run:
  path: concourse-tasks/tasks/configure-cf/task

params:
  BBL_STATE_DIR: bbl-state
  ENV:
  SYSTEM_DOMAIN:
  CF_ORG:
  CF_USER:
  CF_PASSWORD:
  SPACE_PER_CELL: 20
