#!/bin/bash -eux

function close_bbl_ssh_connection() {
  # Kill all ssh connections on exit.
  # This is needed so that tasks using bbl print-env in a credhub environment
  # don't hang after the script is finished.
  pkill ssh || true
}

function setup_bosh_env_vars() {
  set +ux
  pushd bbl-state/"${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd
  set -ux
}

function login_to_credhub() {
  set +x
  echo "Connecting to ${CREDHUB_SERVER}"
  credhub api --server ${CREDHUB_SERVER}
  credhub login
  set -x
}

function get_credhub_login_details() {
  STATE=bbl-state/${BBL_STATE_DIR}/vars/terraform.tfstate
}

function get_cf_login_details() {
  set +x
  CF_ADMIN_PASSWORD=$(credhub get -n /bosh-${ENV}/cf/cf_admin_password --output-json | jq -r  '.value') > /dev/null
  set -x
 
  close_bbl_ssh_connection
  unset https_proxy

  cf api https://api.${SYSTEM_DOMAIN} --skip-ssl-validation
  
  set +x
  cf login -u admin -p ${CF_ADMIN_PASSWORD} -o system
  set -x

  cf create-org ${CF_ORG}

  set +x
  cf create-user ${CF_USER} ${CF_PASSWORD}
  set -x
 
  cf set-org-role ${CF_USER} ${CF_ORG} OrgManager

  #cf create-domain servicedeliverygcp@monitise.com ${GCP_PROJECT}.${DOMAIN}
  cf update-quota default -m ${CF_QUOTA}

  #set -x
}

function main() {
  setup_bosh_env_vars
  get_credhub_login_details
  login_to_credhub
  get_cf_login_details
}

trap close_bbl_ssh_connection EXIT
main

