---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: bosh-repo
- name: concourse-tasks

outputs:
- name: bosh-releases

run:
  path: concourse-tasks/tasks/create-bosh-release/task

params:
  NAME:
