#!/bin/bash -exu

function check_input_params() {
  if [ -z "$NAME" ]; then
    echo "NAME has not been set"
    exit 1
  fi
}

function create_release() {
  pushd "bosh-repo"
    bosh create-release --timestamp-version --tarball=../bosh-releases/${NAME}.tgz
  popd
}


function set_git_config() {
  if [ -z "${GIT_COMMIT_USERNAME}" ]; then
    GIT_COMMIT_USERNAME="CI Bot"
  fi

  if [ -z "${GIT_COMMIT_EMAIL}" ]; then
    GIT_COMMIT_EMAIL="cf-release-integration@pivotal.io"
  fi

  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"
}

function main() {
  local root_dir
  root_dir="${1}"
  check_input_params
  create_release
}

main ${PWD}
