#!/bin/bash -eux

function setup_bosh_env_vars() {
  set +ux
  pushd env-repo/"${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd
  set -ux
}

function close_bbl_ssh_connection() {
  # Kill all ssh connections on exit.
  # This is needed so that tasks using bbl print-env in a credhub environment
  # don't hang after the script is finished.
  pkill ssh || true
}

function deploy() {
  local arguments
  arguments=""
  for op in ${OPS_FILES}
  do
    arguments="${arguments} -o ${op}"
  done

  local files
  files=""
  for var_file in ${VARS_FILES}
  do
    files="${files} -l ${var_file}"
  done

  local vars
  vars=""
  for var in ${VARS}
  do
    vars="${vars} -v ${var}"
  done

  bosh \
    -n \
    -d ${NAME} \
    deploy \
    ${arguments} \
    ${files} \
    ${vars} \
    bosh-repo/${MANIFEST_FILE}
  set -x
}

function main() {
  setup_bosh_env_vars
  deploy
}

trap close_bbl_ssh_connection EXIT

main ${PWD}

