#!/bin/sh


ls ${BBL_STATE_DIR}
VAR_STORE=env-repo/bbl-state/vars/director-vars-store.yml
CREDHUB_PASSWORD=$(bosh int ${VAR_STORE} --path /credhub_cli_password)

CREDHUB_API="${CREDHUB_SERVER}"
echo "Connecting to ${CREDHUB_API}"

STATE=env-repo/bbl-state/vars/terraform.tfstate
terraform output -state=${STATE}

bosh int ${VAR_STORE} --path /credhub_tls/certificate > credhub.cert
bosh int ${VAR_STORE} --path /uaa_ssl/certificate > uaa.cert

cat credhub.cert
cat uaa.cert

bbl print-env
#eval "$(bbl print-env)"
credhub api --server ${CREDHUB_API} --ca-cert=uaa.cert --ca-cert=credhub.cert
credhub login -u credhub-cli -p ${CREDHUB_PASSWORD}

credhub show
