---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: env-repo
- name: concourse-tasks

run:
  path: concourse-tasks/tasks/credhub/task

params:
  SYSTEM_DOMAIN:
