#!/bin/bash -eux

function close_bbl_ssh_connection() {
  # Kill all ssh connections on exit.
  # This is needed so that tasks using bbl print-env in a credhub environment
  # don't hang after the script is finished.
  pkill ssh || true
}

function setup_bosh_env_vars() {
  set +ux
  pushd env-repo/"${BBL_STATE_DIR}"
    bbl print-env
    eval "$(bbl print-env)"
  popd
  set -ux
}

trap close_bbl_ssh_connection EXIT

setup_bosh_env_vars

VAR_STORE=env-repo/${BBL_STATE_DIR}/vars/director-vars-store.yml

echo "Connecting to ${CREDHUB_SERVER}"

STATE=env-repo/${BBL_STATE_DIR}/vars/terraform.tfstate
terraform output -state=${STATE}

bosh int ${VAR_STORE} --path /credhub_tls/certificate > credhub.cert
bosh int ${VAR_STORE} --path /uaa_ssl/certificate > uaa.cert

export https_proxy=${BOSH_ALL_PROXY}

credhub api --server ${CREDHUB_SERVER} --ca-cert=uaa.cert --ca-cert=credhub.cert
credhub login -u ${CREDHUB_USER} -p ${CREDHUB_PASSWORD}

CF_HOST=$(terraform output -state=${STATE} cf_db_host)
UAA_PASSWORD=$(terraform output -state=${STATE} uaa-password)
BBS_PASSWORD=$(terraform output -state=${STATE} bbs-password)
CC_PASSWORD=$(terraform output -state=${STATE} cc-password)
POLICYSERVER_PASSWORD=$(terraform output -state=${STATE} policy_server-password)
ROUTINGAPI_PASSWORD=$(terraform output -state=${STATE} routing_api-password)
SILKCONTROLLER_PASSWORD=$(terraform output -state=${STATE} silk_controller-password)
LOCKET_PASSWORD=$(terraform output -state=${STATE} locket-password)

credhub set -t value -n /bosh-${ENV}/cf/external_database_type -v 'mysql'

credhub set -t value -n /bosh-${ENV}/cf/external_uaa_database_address -v "${CF_HOST}"
credhub set -t password -n /bosh-${ENV}/cf/external_uaa_database_password -w "${UAA_PASSWORD}"
credhub set -t value -n /bosh-${ENV}/cf/external_uaa_database_name -v 'uaa_db'
credhub set -t value -n /bosh-${ENV}/cf/external_uaa_database_username -v 'uaa'

credhub set -t value -n /bosh-${ENV}/cf/external_bbs_database_address -v "${CF_HOST}"
credhub set -t password -n /bosh-${ENV}/cf/external_bbs_database_password -w "${BBS_PASSWORD}"
credhub set -t value -n /bosh-${ENV}/cf/external_bbs_database_name -v 'bbs_db'
credhub set -t value -n /bosh-${ENV}/cf/external_bbs_database_username -v 'bbs'

credhub set -t value -n /bosh-${ENV}/cf/external_cc_database_address -v "${CF_HOST}"
credhub set -t password -n /bosh-${ENV}/cf/external_cc_database_password -w "${CC_PASSWORD}"
credhub set -t value -n /bosh-${ENV}/cf/external_cc_database_name -v 'cc_db'
credhub set -t value -n /bosh-${ENV}/cf/external_cc_database_username -v 'cc'

credhub set -t value -n /bosh-${ENV}/cf/external_routing_api_database_address -v "${CF_HOST}"
credhub set -t password -n /bosh-${ENV}/cf/external_routing_api_database_password -w "${ROUTINGAPI_PASSWORD}"
credhub set -t value -n /bosh-${ENV}/cf/external_routing_api_database_name -v 'routing_api_db'
credhub set -t value -n /bosh-${ENV}/cf/external_routing_api_database_username -v 'routing_api'

credhub set -t value -n /bosh-${ENV}/cf/external_policy_server_database_address -v "${CF_HOST}"
credhub set -t password -n /bosh-${ENV}/cf/external_policy_server_database_password -w "${POLICYSERVER_PASSWORD}"
credhub set -t value -n /bosh-${ENV}/cf/external_policy_server_database_name -v 'policy_server_db'
credhub set -t value -n /bosh-${ENV}/cf/external_policy_server_database_username -v 'policy_server'

credhub set -t value -n /bosh-${ENV}/cf/external_silk_controller_database_address -v "${CF_HOST}"
credhub set -t password -n /bosh-${ENV}/cf/external_silk_controller_database_password -w "${SILKCONTROLLER_PASSWORD}"
credhub set -t value -n /bosh-${ENV}/cf/external_silk_controller_database_name -v 'silk_controller_db'
credhub set -t value -n /bosh-${ENV}/cf/external_silk_controller_database_username -v 'silk_controller'

credhub set -t value -n /bosh-${ENV}/cf/external_locket_database_address -v "${CF_HOST}"
credhub set -t password -n /bosh-${ENV}/cf/external_locket_database_password -w "${LOCKET_PASSWORD}"
credhub set -t value -n /bosh-${ENV}/cf/external_locket_database_name -v 'locket_db'
credhub set -t value -n /bosh-${ENV}/cf/external_locket_database_username -v 'locket'

credhub set -t value -n /bosh-${ENV}/cf/app_package_directory_key -v 'bosh-${ENV}-package'
credhub set -t value -n /bosh-${ENV}/cf/buildpack_directory_key -v 'bosh-${ENV}-buildpack'
credhub set -t value -n /bosh-${ENV}/cf/droplet_directory_key -v 'bosh-${ENV}-droplet'
credhub set -t value -n /bosh-${ENV}/cf/resource_directory_key -v 'bosh-${ENV}-resource'

credhub set -t password -n /bosh-${ENV}/cf/blobstore_access_key_id -w ''
credhub set -t password -n /bosh-${ENV}/cf/blobstore_secret_access_key -w ''

credhub find
