---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: bbl-state
- name: concourse-tasks
- name: cf-deployment-concourse-tasks

run:
  path: concourse-tasks/tasks/run-errand/task

params:
  BBL_STATE_DIR: bbl-state
  DEPLOYMENT_NAME: cf
  ERRAND_NAME: 
