#!/bin/bash -eux

function close_bbl_ssh_connection() {
  # Kill all ssh connections on exit.
  # This is needed so that tasks using bbl print-env in a credhub environment
  # don't hang after the script is finished.
  pkill ssh || true
}

function setup_bosh_env_vars() {
  set +ux
  pushd env-repo/"${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd
  set -ux
}

function login_to_credhub() {
  set +x
  echo "Connecting to ${CREDHUB_SERVER}"
  export https_proxy=${BOSH_ALL_PROXY}
  credhub api --server ${CREDHUB_SERVER} --ca-cert=uaa.cert --ca-cert=credhub.cert
  credhub login -u ${CREDHUB_USER} -p ${CREDHUB_PASSWORD}
  set -x
}

function get_terraform_outputs() {
  VAR_STORE=env-repo/${BBL_STATE_DIR}/vars/director-vars-store.yml
  STATE=env-repo/${BBL_STATE_DIR}/vars/terraform.tfstate
  bosh int ${VAR_STORE} --path /credhub_tls/certificate > credhub.cert
  bosh int ${VAR_STORE} --path /uaa_ssl/certificate > uaa.cert
}

function set_credhub_config() {
  set +x
  credhub set -t value -n /bosh-${ENV}/cf/stackdriver_project_id -v "${STACKDRIVER_PROJECT}" > /dev/null
  credhub set -t value -n /bosh-${ENV}/cf/stackdriver_credentials_json -v "${STACKDRIVER_ACCOUNT_KEY}" > /dev/null
  set -x
}

trap close_bbl_ssh_connection EXIT

setup_bosh_env_vars

get_terraform_outputs
login_to_credhub
set_credhub_config

