#!/bin/bash -eux

function close_bbl_ssh_connection() {
  # Kill all ssh connections on exit.
  # This is needed so that tasks using bbl print-env in a credhub environment
  # don't hang after the script is finished.
  pkill ssh || true
}

function setup_bosh_env_vars() {
  set +ux
  pushd env-repo/"${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd
  set -ux
}

function login_to_credhub() {
  set +x
  echo "Connecting to ${CREDHUB_SERVER}"
  export https_proxy=${BOSH_ALL_PROXY}
  #credhub api --server ${CREDHUB_SERVER} --ca-cert=uaa.cert --ca-cert=credhub.cert
  credhub login -u ${CREDHUB_USER} -p ${CREDHUB_PASSWORD}
  set -x
}

function set_value() {
  set +x
  if [ "${TYPE}" == "value" ]; then
    credhub set -t value -n ${PATH} -v "${VALUE}" > /dev/null
  elif [ "${TYPE}" == "password" ]; then
    credhub set -t password -n ${PATH} -w "${VALUE}" > /dev/null
  else 
  	echo "Unknown ${TYPE} for ${PATH}"
    exit 1
  fi
  set -x
}

trap close_bbl_ssh_connection EXIT

setup_bosh_env_vars

get_terraform_outputs
login_to_credhub
set_value

